# app相关基础信息
app:
  name: "Website Monitor"
  runType: "dev"

# http服务
httpServer:
  open: true
  prod: 18888

# udp服务
udpServer:
  open: true
  prod: 18889

# user
user:
  -
    name: "admin"
    password: "123"

# jwt设置
jwt:
  secret: "website-monitor"
  expire: 86400

# 存放监测日志的路径
logPath: "./log/"

connCode: qwert
connSecret: abc123!@